version: '3.8'
services:
  db:
    container_name: db
    image: mysql:latest
    ports:
      - '3307:3306'
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=desafio-nodis
    command: --default-authentication-plugin=mysql_native_password
  app:
    image: node:15.12.0-alpine3.10
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/app
      - /node_modules
    depends_on:
      - db
    working_dir: /usr/app
    environment:
      - DB=db
    command: sh -c "./wait-for db:3306 -t 60  -- echo 'Installing node_modules...' && npm i && npm start"