version: '3'
services:
  db:
    container_name: db
    image: mysql:latest
    ports:
      - '3307:3306'
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=desafio-nodis
    command: --default-authentication-plugin=mysql_native_password
  app:
    build: .
    ports:
        - '3001:3001'
    volumes:
      - .:/usr/app
    depends_on:
        - db
    command: ["./wait-for.sh", "db:3306", "-t", "60",  "--", "npm", "start"]